# Site settings
title: Lush Sleutsky's Blog
header-img: img/home-bg.png
email: lushsleutsky@gmail.com
copyright_name: LSleutsky
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: @LSleutsky
github_username:  LSleutsky
learn_profile: LSleutsky
email_username: lushsleutsky@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
